#!/usr/bin/env Rscript

#######################################
### ---- Some Global variables ---- ###
#######################################

# Separation between features to use in Correspondence analysis
FEATURES_TO_USE <- c(
  "GCT",
  "GCC",
  "GCA",
  "GCG",
  "CGT",
  "CGC",
  "CGA",
  "CGG",
  "AGA",
  "AGG",
  "AAT",
  "AAC",
  "GAT",
  "GAC",
  "TGT",
  "TGC",
  "CAA",
  "CAG",
  "GAA",
  "GAG",
  "GGT",
  "GGC",
  "GGA",
  "GGG",
  "CAT",
  "CAC",
  "ATT",
  "ATC",
  "ATA",
  "TTA",
  "TTG",
  "CTT",
  "CTC",
  "CTA",
  "CTG",
  "AAA",
  "AAG",
  #"ATG",
  "TTT",
  "TTC",
  "CCT",
  "CCC",
  "CCA",
  "CCG",
  "TCT",
  "TCC",
  "TCA",
  "TCG",
  "AGT",
  "AGC",
  "ACT",
  "ACC",
  "ACA",
  "ACG",
  #"TGG",
  "TAT",
  "TAC",
  "GTT",
  "GTC",
  "GTA",
  "GTG"#,
  #"TAA",
  #"TAG",
  #"TGA"
)

QUANTI_SUPP_FEATURES <- c(
  "gc3",
  "gc12",
  "enc",
  "cai_values",
  "AA",
  "AC",
  "AG",
  "AT",
  "CA",
  "CC",
  "CG",
  "CT",
  "GA",
  "GC",
  "GG",
  "GT",
  "TA",
  "TC",
  "TG",
  "TT",
  "A",
  "C",
  "G",
  "T", #"other"
  "gc",
  "aromatic_prct",
  "gravy_scores"
)

# Nucleotides and dinucleotides lists
NUCLEOTIDES <- c("A", "C", "G", "T")
DINUCLEOTIDES <- c("AA", "AC", "AG", "AT", "CA", "CC", "CG", "CT", 
                   "GA", "GC", "GG", "GT", "TA", "TC", "TG", "TT")

# Amino acids and their associated codons
CODON_DICT <- list(
  Ala = c("GCT", "GCC", "GCA", "GCG"),
  Arg = c("CGT", "CGC", "CGA", "CGG", "AGA", "AGG"),
  Asn = c("AAT", "AAC"),
  Asp = c("GAT", "GAC"),
  Cys = c("TGT", "TGC"),
  Gln = c("CAA", "CAG"),
  Glu = c("GAA", "GAG"),
  Gly = c("GGT", "GGC", "GGA", "GGG"),
  His = c("CAT", "CAC"),
  Ile = c("ATT", "ATC", "ATA"),
  Leu = c("TTA", "TTG", "CTT", "CTC", "CTA", "CTG"),
  Lys = c("AAA", "AAG"),
  Met = c("ATG"),
  Phe = c("TTT", "TTC"),
  Pro = c("CCT", "CCC", "CCA", "CCG"),
  Ser = c("TCT", "TCC", "TCA", "TCG", "AGT", "AGC"),
  Thr = c("ACT", "ACC", "ACA", "ACG"),
  Trp = c("TGG"),
  Tyr = c("TAT", "TAC"),
  Val = c("GTT", "GTC", "GTA", "GTG"),
  Stop = c("TAA", "TAG", "TGA")
)